---
application:
  name: "web-shopping-backend"
  project: "backend"
  organization: "QoveryCommunity"
  storage:
  - name: "/"
    size: "10"
    type: "fast_ssd"
    mount_point: "/mnt//"
routers:
- name: "main-web-shopping-backend"
  routes:
  - application_name: "web-shopping-backend"
    paths:
    - "/*"
