---
application:
  name: "web-shopping-backend"
  project: "web3-shppoing-backend"
  organization: "QoveryCommunity"
  storage:
  - name: "images"
    size: "10"
    type: "fast_ssd"
    mount_point: "/mnt/images"
routers:
- name: "main-web-shopping-backend"
  routes:
  - application_name: "web-shopping-backend"
    paths:
    - "/*"
